# Generated by Django 5.0.4 on 2024-04-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('body_color', models.CharField(default='white', max_length=50, verbose_name='ボディ')),
                ('body_text', models.CharField(default='black', max_length=50, verbose_name='テキストカラー')),
                ('head', models.CharField(default='lightgray', max_length=50, verbose_name='ヘッダー')),
                ('head_text', models.CharField(default='black', max_length=50, verbose_name='ヘッダーテキスト')),
                ('footer', models.CharField(default='lightgray', max_length=50, verbose_name='フッター')),
                ('footer_text', models.CharField(default='black', max_length=50, verbose_name='フッターテキスト')),
                ('app', models.BooleanField(default=True, help_text='適用する場合はチェック', verbose_name='公開する')),
            ],
            options={
                'verbose_name': 'カラー設定',
                'verbose_name_plural': 'カラー設定',
            },
        ),
    ]
