# Generated by Django 5.0.4 on 2024-04-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcolor',
            name='body_color',
        ),
        migrations.RemoveField(
            model_name='blogcolor',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='blogcolor',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='blogcolor',
            name='head',
        ),
        migrations.RemoveField(
            model_name='blogcolor',
            name='title',
        ),
        migrations.AddField(
            model_name='blogcolor',
            name='body_bg',
            field=models.CharField(default='white', max_length=50, verbose_name='ボディ背景'),
        ),
        migrations.AddField(
            model_name='blogcolor',
            name='code_bg',
            field=models.CharField(default='black', max_length=50, verbose_name='コードブロック背景'),
        ),
        migrations.AddField(
            model_name='blogcolor',
            name='code_texxt',
            field=models.CharField(default='white', max_length=50, verbose_name='コードテキスト'),
        ),
        migrations.AddField(
            model_name='blogcolor',
            name='head_bg',
            field=models.CharField(default='lightgray', max_length=50, verbose_name='ヘッダー背景'),
        ),
        migrations.AddField(
            model_name='blogcolor',
            name='theme_name',
            field=models.CharField(default='Default', max_length=50, verbose_name='テーマ名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcolor',
            name='title_bg',
            field=models.CharField(default='lightgray', max_length=50, verbose_name='タイトル背景'),
        ),
        migrations.AddField(
            model_name='blogcolor',
            name='title_text',
            field=models.CharField(default='black', max_length=50, verbose_name='タイトルテキスト'),
        ),
        migrations.AlterField(
            model_name='blogcolor',
            name='body_text',
            field=models.CharField(default='black', max_length=50, verbose_name='ボディテキスト'),
        ),
    ]
