# Generated by Django 5.0.4 on 2024-05-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_color_alter_blogcolor_body_bg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='color',
        ),
    ]
